other-metadata: LICENSE
gentoo/policy-guide pull request #12
Opened 2020-02-11 10:07 UTC by mgorny

Closes: https://bugs.gentoo.org/709020
Signed-off-by: Michał Górny <mgorny@gentoo.org>

2020-02-11 10:12 UTC, SoapGentoo approved these changes

2020-02-11 11:08 UTC, ulm commented on other-metadata.rst
> +the licenses of those dependencies need to be listed as well.  This
```suggestion
the licenses of these dependencies need to be listed as well.  This
```

2020-02-11 11:08 UTC, ulm commented on other-metadata.rst
> +is not strictly required when statically linking to dependencies
```suggestion
is not required when statically linking to dependencies
```

I think we don't want packages to list licenses of any libraries that they're not installing.

2020-02-11 11:08 UTC, ulm commented on other-metadata.rst
> +the package.
What do you mean by this? Do we have any build tools that don't allow to build some things?

2020-02-11 11:08 UTC, ulm commented on other-metadata.rst
> +for this to work effectively, the packages must provide correct
```suggestion
for this to work effectively, the packages must provide a correct
```

2020-02-11 11:08 UTC, ulm commented on other-metadata.rst
> +on user's system and they do not affect the runtime use of packages.
```suggestion
on the user's system and they do not affect the runtime use of packages.
```

2020-02-11 15:26 UTC, mgorny commented on other-metadata.rst
> +the package.
I don't have a specific example. However, if license terms can prohibit you from using some program, then I suppose they can also prohibit you from running it at build time.

2020-02-11 15:29 UTC, mgorny commented
Merged all the suggestions.

2020-02-11 16:11 UTC, ulm commented on other-metadata.rst
> +the package.
IMHO this has little to do with LICENSE labelling. So I'd suggest to drop the sentence for now, especially if there isn't any concrete example.

(Also note that a license can only prevent me from running a program if I accept it first, but nothing forces me to accept a license unless it is an EULA. So we're talking about EULA build-time dependencies here.)

2020-02-11 16:53 UTC, mgorny commented on other-metadata.rst
> +the package.
Removed it then.

2020-02-12 05:28 UTC, robbat2 approved these changes

2020-02-12 05:28 UTC, robbat2 commented on other-metadata.rst
> +by different licenses.  Listing all of them is the simplest way
`all of them` -> `listing all licenses`

2020-02-12 05:28 UTC, robbat2 commented on other-metadata.rst
> +This is enforced for bundled dependencies but not for static linking
Start a new paragraph here. `\n\nListing of licenses is enforced for bundled dependencies...`

2020-02-12 05:28 UTC, robbat2 commented on other-metadata.rst
> +is not required when statically linking to dependencies
`This is not presently required`

2020-02-13 16:11 UTC, mgorny commented
Thanks, Robin, I've applied all your suggestions.

2020-02-14 10:38 UTC, Zlogene requested changes

2020-02-14 10:38 UTC, Zlogene commented on other-metadata.rst
> +If the package bundles any dependencies that are either installed,
```suggestion
If a package bundles any dependencies that are either installed,
```

2020-02-14 10:38 UTC, Zlogene commented on other-metadata.rst
> +installed by separate Gentoo packages.
```suggestion
installed by separate packages in the repository.
```

2020-02-14 10:38 UTC, Zlogene commented on other-metadata.rst
> +*Rationale*: the primary purpose of the license support in package
```suggestion
*Rationale*: the primary purpose of the license support in the package
```

2020-02-14 10:38 UTC, Zlogene commented on other-metadata.rst
> +on the user's system and they do not affect the runtime use of packages.
```suggestion
on the user's system and do not affect the runtime use of packages.
```

2020-02-14 11:56 UTC, mgorny commented
All applied.

2020-02-18 17:02 UTC, Zlogene approved these changes

2020-02-18 17:09 UTC, SoapGentoo approved these changes

2020-02-18 17:26 UTC, ulm approved these changes

2020-02-18 18:53 UTC, akhuettel approved these changes

2020-02-21 11:07 UTC, closed without merging