dependencies: include optfeature
gentoo/policy-guide pull request #3
Opened 2020-01-12 07:35 UTC by juippis

2020-01-12 10:06 UTC, mgorny requested changes
If there is no preference, then you can't say something is preferred.

2020-01-12 10:13 UTC, juippis commented
Switched to *suggested*.

2020-01-14 13:09 UTC, mgorny commented
It's still the same deal. Either we don't have a recommendation or we do. I've copied the paragraph on not having a recommendation from wiki page. If we believe we should recommend one way or another, please make it say so explicitly. Then we can vote on it as policy change.

2020-01-14 17:15 UTC, juippis commented
Updated to a very simple form honoring original wording.

2020-01-14 17:25 UTC, mgorny commented on dependencies.rst
> +of optional runtime dependencies. Three possible ways are
```suggestion
of optional runtime dependencies.  Three possible ways are 
```

2020-01-15 07:28 UTC, Zlogene approved these changes

2020-01-21 16:01 UTC, mgorny approved these changes

2020-01-21 16:17 UTC, SoapGentoo approved these changes

2020-01-21 16:40 UTC, ulm approved these changes

2020-01-21 16:46 UTC, closed without merging